# Generated by Django 3.2.5 on 2021-07-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentincollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_general_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyshortdiscription', models.CharField(max_length=300, null=True)),
                ('facultyabout', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='proftype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profdesname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('emailaddress', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('usertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Assistance.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='notice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticetile', models.CharField(max_length=100, null=True)),
                ('noticecontent', models.TextField(null=True)),
                ('noticetag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Assistance.topics')),
                ('postuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Assistance.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='facultycabinoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyoffice', models.TextField(null=True)),
                ('collegeidoffaculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Assistance.faculty_general_information')),
            ],
        ),
        migrations.AddField(
            model_name='faculty_general_information',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Assistance.user_detail'),
        ),
    ]
